directory: /data/media/music/1_current
library: ~/.config/beets/musiclibrary.db

# pip install --user beets[fromfilename,fetchart,lyrics,edit,embedart,lastgenre]

plugins: fromfilename edit embedart fetchart lyrics lastgenre

# Keep your current directory structure; importing should never move or copy files but instead just correct the tags on music
import:
  move: yes
  copy: no
  write: yes

paths:
  default: albums/$albumartist/$album%aunique{}/$track - $artist - $title
  singleton: $artist - $title
  comp: $artist - $title

fetchart:
  sources: filesystem coverart amazon albumart wikipedia fanarttv google


